# Generated by Django 4.2.20 on 2025-04-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("engineer", "Engineer"),
                    ("team-leader", "Team Leader"),
                    ("department-leader", "Department Leader"),
                    ("senior-manager", "Senior Manager"),
                    ("admin", "Admin"),
                ],
                max_length=50,
            ),
        ),
    ]
