# Generated by Django 5.1.5 on 2025-04-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('team-leader', 'Team Leader'), ('department-leader', 'Department Leader'), ('senior-manager', 'Senior Manager')], max_length=50),
        ),
    ]
