# Generated by Django 5.1.5 on 2025-04-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='comments',
        ),
    ]
